### ISSUE TITLE
ARCHIVEFACEBOOK HELP NEEDED

### ISSUE THREAD

**Issue by garychristensenshow** [machawk1/archivefacebook#1]
I have downloaded the Firefox - ArchiveFacebook :: Add-ons for Firefox http://ow.ly/ZYLkj  However the tab is not appearing and app does not work.  Can someone please help???  garychristensenshow@gmail.com

**Comment by machawk1** [comment]
@garychristensenshow This tool is not currently actively support but will be need of a complete overhaul very soon, as Firefox has changed the way add-ons need to be coded. In the meantime, I installed the latest version and was able to replicate your issue of not showing the "tab", which I presume you mean the ArchiveFacebook icon. More recent versions of FireFox hide this icon by default. To re-enable it, right-click on the browser toolbar where other add-ons' icons reside, select "Customize..." then drag the ArchiveFacebook icon to your toolbar.

**Comment by garychristensenshow** [comment]
machhaw1.   Thanks for your help.  I followed your directions and got the icon on the tool bar.  Next I went through every combination to download, backup facebook data but nothing worked.  What am I doing wrong?  o is the program nonfunctionable???  garychristensenshow@gmail.com

**Comment by garychristensenshow** [comment]
Hello machawk1.  I have followed your instructions and the tab is on the task bar.  However i am unable to save any data from facebook.  I have tried all options.  What am I doing wrong??? Please help   Gary   garychristensenshow@gmail.com
