### ISSUE TITLE
ARCHIVEFACEBOOK ASSISTANCE PLEASE

### ISSUE THREAD

**Issue by garychristensenshow** [machawk1/archivefacebook#2]
I have downloaded the Firefox - ArchiveFacebook :: Add-ons for Firefox http://ow.ly/ZYLkj  However the tab is not appearing and app does not work.  Can someone please help???  garychristensenshow@gmail.com

**Comment by machawk1** [comment]
Assistance provided in #1. Please open another issue detailing the specifics of any further issues you encounter.
